name: build-and-release
on: [push]
jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release --all-features
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/alik.exe
