name: cargo-build
on: [push]
jobs:
  build-app:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - uses: actions/upload-artifact@v3
        with:
            name: alik-exe
            path: target\release\alik.exe
            retention-days: 1
  